[pkgs]
python3 = "python"
postgresql = "postgresql"
gcc = "gcc"

[steps.build]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[steps.start]
commands = [
  "gunicorn jeros.wsgi:application --bind 0.0.0.0:$PORT"
]
